<div style="width:1000 px">

<div style="float:right; width:98 px; height:98px;"><img src="https://pbs.twimg.com/profile_images/1187259618/unidata_logo_rgb_sm_400x400.png" alt="Unidata Logo" style="height: 98px;"></div>

<h1>NumPy Primer</h1>
<h3>Unidata Python Workshop</h3>

<div style="clear:both"></div>
</div>

<hr style="height:2px;">

<div style="float:right; width:250 px"><img src="http://www.contribute.geeksforgeeks.org/wp-content/uploads/numpy-logo1.jpg" alt="NumPy Logo" style="height: 250px;"></div>


## Overview:

* **Teaching:** 20 minutes
* **Exercises:** 10 minutes

### Questions
1. What are arrays?
2. How can arrays be manipulated effectively in Python?

### Objectives
1. Create an array of ‘data’.
2. Perform basic calculations on this data using python math functions.
3. Slice and index the array
4. Perform a meteorological calculation on an array of data using MetPy.

NumPy is the fundamental package for scientific computing with Python. It contains among other things:
- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- useful linear algebra, Fourier transform, and random number capabilities

The NumPy array object is the common interface for working with typed arrays of data across a wide-variety of scientific Python packages. NumPy also features a C-API, which enables interfacing existing Fortran/C/C++ libraries with Python and NumPy.

## 1. Create an array of 'data' and slice/index it

The NumPy array represents a *contiguous* block of memory, holding entries of a given type (and hence fixed size). The entries are laid out in memory according to the shape, or list of dimension sizes.

In [5]:
# Convention for import to get shortened namespace
import numpy as np

In [6]:
# Create a simple array from a list of integers
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [7]:
# Print out the shape attribute
a.shape

(3,)

In [8]:
# Print out the data type attribute
a.dtype

dtype('int64')

In [9]:
# This time use a list of floats
a = np.array([1., 2., 3., 4., 5.])
a

array([ 1.,  2.,  3.,  4.,  5.])

In [10]:
# Print out the shape attribute
a.shape

(5,)

In [11]:
# Print out the data type attribute
a.dtype

dtype('float64')

NumPy also provides helper functions for generating arrays of data to save you typing for regularly spaced data. 

* `arange(start, stop, interval)` creates a range of values in the interval `[start,stop)` with `step` spacing.
* `linspace(start, stop, num)` creates a range of `num` evenly spaced values over the range `[start,stop]`.

### arange

In [12]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [13]:
a = np.arange(3, 11)
print(a)

[ 3  4  5  6  7  8  9 10]


In [14]:
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


### linspace

In [15]:
b = np.linspace(5, 15, 5)
print(b)

[  5.    7.5  10.   12.5  15. ]


In [16]:
b = np.linspace(2.5, 10.25, 11)
print(b)

[  2.5     3.275   4.05    4.825   5.6     6.375   7.15    7.925   8.7
   9.475  10.25 ]


## 2. Perform basic calculations with Python

### Basic math

In core Python, adding the numbers of two lists or arrays element-wise explicitly would look like this:

In [17]:
a = np.arange(5, 10)
b = np.linspace(3, 4.5, 5)

In [18]:
print([x + y for x,y in zip(a,b)])

[8.0, 9.375, 10.75, 12.125, 13.5]


That is very verbose and not very intuitive. Using NumPy this becomes:

In [19]:
a + b

array([  8.   ,   9.375,  10.75 ,  12.125,  13.5  ])

The four major mathematical operations operate in the same way. They perform an element-by-element calculation of the two arrays. The two must be the same shape though!

In [20]:
a * b

array([ 15.  ,  20.25,  26.25,  33.  ,  40.5 ])

### Constants

NumPy proves us access to some useful constants as well - remember you should never be typing these in manually! Other libraries such as SciPy and MetPy have their own set of constants that are more domain specific.

In [21]:
np.pi

3.141592653589793

In [22]:
np.e

2.718281828459045

In [23]:
# This makes working with radians effortless!
t = np.arange(0, 2 * np.pi + np.pi / 4, np.pi / 4)
t

array([ 0.        ,  0.78539816,  1.57079633,  2.35619449,  3.14159265,
        3.92699082,  4.71238898,  5.49778714,  6.28318531])

### Array math functions

NumPy also has math functions that can operate on arrays. Similar to the math operations, these greatly simplify and speed up these operations. Be sure to checkout the [listing](https://docs.scipy.org/doc/numpy/reference/routines.math.html) of mathematical functions in the NumPy documentation.

In [24]:
# Calculate the sine function
sin_t = np.sin(t)
print(sin_t)

[  0.00000000e+00   7.07106781e-01   1.00000000e+00   7.07106781e-01
   1.22464680e-16  -7.07106781e-01  -1.00000000e+00  -7.07106781e-01
  -2.44929360e-16]


In [25]:
# Round to three decimal places
print(np.round(sin_t,3))

[ 0.     0.707  1.     0.707  0.    -0.707 -1.    -0.707 -0.   ]


In [26]:
# Calculate the cosine function
cos_t = np.cos(t)
print(cos_t)

[  1.00000000e+00   7.07106781e-01   6.12323400e-17  -7.07106781e-01
  -1.00000000e+00  -7.07106781e-01  -1.83697020e-16   7.07106781e-01
   1.00000000e+00]


In [27]:
# Convert radians to degrees
degrees = np.rad2deg(t)
print(degrees)

[   0.   45.   90.  135.  180.  225.  270.  315.  360.]


In [28]:
# Integrate the sine function with the trapezoidal rule
sine_integral = np.trapz(sin_t, t)
print(np.round(sine_integral, 3))

-0.0


In [29]:
# Sum the values of the cosine
cos_sum = np.sum(cos_t)
print(cos_sum)

1.0


In [30]:
# Calculate the cumulative sum of the cosine
cos_csum = np.cumsum(cos_t)
print(cos_csum)

[  1.00000000e+00   1.70710678e+00   1.70710678e+00   1.00000000e+00
   0.00000000e+00  -7.07106781e-01  -7.07106781e-01  -4.44089210e-16
   1.00000000e+00]


## 3. Slice and index the array

Indexing is how we pull individual data items out of an array. Slicing extends this process to pulling out a regular set of the items.

In [31]:
# Create an array for testing
a = np.arange(12).reshape(3, 4)

In [32]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Indexing in Python is 0-based, so the command below looks for the 2nd item along the first dimension and the 3rd along the second dimension.

In [33]:
a[1, 2]

6

Can also just index on one dimension

In [34]:
a[2]

array([ 8,  9, 10, 11])

Negative indices are also allowed, which permit indexing relative to the end of the array.

In [35]:
a[0, -1]

3

Slicing syntax is written as `start:stop[:step]`, where all numbers are optional.
- defaults: 
  - start = 0
  - end = len(dim)
  - step = 1
- The second colon is also optional if no step is used.

It should be noted that end represents one past the last item; one can also think of it as a half open interval: `[start, end)`

In [36]:
a[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
a[::2, ::2]

array([[ 0,  2],
       [ 8, 10]])

In [38]:
a[:, 2]

array([ 2,  6, 10])

In [39]:
# ... can be used to replace one or more full slices
a[..., 2]

array([ 2,  6, 10])

## Exercises

Using the data below, write code to solve the commented problems.

In [40]:
a = np.arange(60).reshape(3, 4, 5)

In [41]:
# Grab every 3rd item from each dimension

In [42]:
# Pull out the 2nd 4x5 slice

In [43]:
# Grab the last column from all dimensions (result should be 3x4)

## 4. Perform a meteorological calculation on an array of data using MetPy.

In [48]:
u = np.random.randint(0,45,10)
v = np.random.randint(0,45,10)

In [49]:
print(u)
print(v)

[22 38  4 27 38 36 17 34 38  3]
[ 5 18 18 27  7 44 17  8 15  9]


In [50]:
import metpy.calc as mpcalc

speed = mpcalc.get_wind_speed(u, v)
direction = mpcalc.get_wind_dir(u, v)

In [52]:
print(speed)
print(np.rad2deg(direction))

[ 22.56102835  42.04759208  18.43908891  38.18376618  38.63935817
  56.85068161  24.04163056  34.92849839  40.85339643   9.48683298]
[ 257.19573393  244.65382406  192.52880771  225.          259.56252465  219.28940686  225.          256.75948008  248.45902408  198.43494882] degree


In [53]:
print(np.mean(speed))

32.603187368


In [56]:
print(np.mean(np.rad2deg(direction)))
print(np.std(np.rad2deg(direction)))

232.68837502024962 degree
23.190464898765267 degree


## Resources

The goal of this tutorial is to provide an overview of the use of the NumPy library. It tries to hit all of the important parts, but it is by no means comprehensive. For more information, try looking at the:
- [Tentative NumPy Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)
- [NumPy User Guide](http://docs.scipy.org/doc/numpy/user/)
- [Introduction to NumPy from SAM](http://www.sam.math.ethz.ch/~raoulb/teaching/PythonTutorial/intro_numpy.html)